server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: "classpath:ssl/keystore.p12"
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: "PKCS12"

spring:
  data:
    redis:
      host: i10a610.p.ssafy.io
      port: 6379
      password: ${REDIS_PASSWORD}
  config:
    import: optional:env/env.yml

rabbitmq:
  host: i10a610.p.ssafy.io
  port: 4672
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  exchange: togeball.exchange
  matching:
    queue: matching.notification.queue
    routing-key: togeball.matching

openai:
  api:
    key: ${GPT_API_KEY}